plugins {
    id 'com.android.application' version '9.3.0' apply false
    id 'com.android.library' version '9.3.0' apply false
    id 'androidx.navigation.safeargs' version '2.9.8' apply false
    id 'com.google.dagger.hilt.android' version '2.60.1' apply false
    id 'com.google.devtools.ksp' version '2.3.10' apply false
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
